# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
#  workflow_dispatch:
#    inputs:
#      branch:
#        description: 'Branch to use'     
#        required: true
#        default: 'testnew'
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
     branches:
       main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Download Pritunl Client
        run: |
          wget https://client.pritunl.com/pkgs/pritunl-client.deb -O pritunl-client.deb

      - name: Install Pritunl Client
        run: |
          sudo dpkg -i pritunl-client.deb
          sudo apt-get install -f   # Install any missing dependencies
      
      - name: Configure Pritunl Client
        run: |
          echo "server: 'http://35.84.238.102'" >> ~/.pritunl.conf
          echo "username: test" >> ~/.pritunl.conf
          echo "password: 123456" >> ~/.pritunl.conf
          echo "profile: 'srh - test'" >> ~/.pritunl.conf
      
      - name: Connect to Pritunl VPN
        run: sudo pritunl-client start -c ~/.pritunl.conf

      - name: Verify VPN Connection
        run: sudo pritunl-client status


      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: create to

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        if: always()     
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
