name: Scheduled 5-Minute Interval Workflow

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'  # Triggers every 5 minutes

jobs:
  scheduled-task:
    runs-on: ubuntu-latest
    steps:
      - name: Display current time
        run: echo "This workflow was triggered at $(date)"
