name: Scheduled 5-Minute Interval Workflow

on:
  workflow_dispatch:

jobs:
  scheduled-task:
    runs-on: ubuntu-latest
    steps:
      - name: Display current time
        run: echo "This workflow was triggered at $(date)"
